# Generated by Django 4.2.4 on 2023-08-30 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_ordermedicine_order_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='medicine',
        ),
    ]
