# Generated by Django 4.2.4 on 2023-08-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_order_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='medicine',
            field=models.ManyToManyField(through='common.OrderMedicine', to='common.medicine'),
        ),
    ]
