# Generated by Django 4.2.4 on 2023-09-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_order_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('updatetime', models.DateTimeField()),
                ('tag', models.CharField(max_length=200)),
                ('del_flag', models.SmallIntegerField(default=0)),
                ('del_time', models.DateTimeField()),
            ],
        ),
    ]
