# Generated by Django 4.2.4 on 2023-09-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_illustration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illustration',
            name='address',
        ),
        migrations.AddField(
            model_name='illustration',
            name='illu',
            field=models.ImageField(default=1, upload_to='illus'),
            preserve_default=False,
        ),
    ]
