# Generated by Django 4.2.4 on 2023-09-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_illustration_address_illustration_illu'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustration',
            name='author',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
