# Generated by Django 4.2.4 on 2023-09-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_illustration_del_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlluPic',
            fields=[
                ('picid', models.AutoField(primary_key=True, serialize=False)),
                ('picname', models.CharField(max_length=200)),
                ('illu', models.ImageField(upload_to='illustration')),
            ],
        ),
    ]
