# Generated by Django 4.2.4 on 2023-11-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_illupic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illustration',
            name='tag',
        ),
        migrations.AddField(
            model_name='illustration',
            name='feature',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='illustration',
            name='source',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
