# Generated by Django 4.2.4 on 2023-11-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_illustration_illu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illupic',
            name='illu',
            field=models.CharField(max_length=200),
        ),
    ]
